[project]
name = "translation-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "baml-py==0.87.2",
    "google-genai==1.14.0",
    "streamlit>=1.44",
]

[tool.uv.workspace]
members = [
    "modules",
]
